# Generated by Django 4.0.4 on 2022-06-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
