# Generated by Django 4.0.4 on 2022-06-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_remove_image_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ManyToManyField(null=True, to='pool.comment'),
        ),
    ]
