# Generated by Django 4.0.4 on 2022-06-08 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0005_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
